Repository StyledStrike/gmod-glide, pull requests merged in 2024-12, with the labels that each got.

#3 Add power distribution to cars
  lua/entities/base_glide/sv_wheels.lua
  lua/entities/base_glide_car/init.lua
  lua/entities/base_glide_car/shared.lua
  lua/entities/base_glide_car/sv_engine.lua
  lua/entities/base_glide_motorcycle/init.lua
  lua/entities/base_glide_motorcycle/shared.lua
  lua/entities/gtav_airbus.lua
  lua/entities/gtav_blazer.lua
  lua/entities/gtav_dukes.lua
  lua/entities/gtav_gauntlet_classic.lua
  lua/entities/gtav_sanchez.lua
  lua/entities/gtav_speedo.lua
  lua/entities/gtav_wolfsbane.lua
Labels: enhancement

#4 Refactor wheel traction
  lua/entities/base_glide/sv_wheels.lua
  lua/entities/base_glide_aircraft/init.lua
  lua/entities/base_glide_car/init.lua
  lua/entities/base_glide_car/shared.lua
  lua/entities/base_glide_car/sv_engine.lua
  lua/entities/base_glide_motorcycle/init.lua
  lua/entities/base_glide_motorcycle/shared.lua
  lua/entities/base_glide_tank/init.lua
  lua/entities/glide_wheel/init.lua
  lua/entities/gtav_airbus.lua
  lua/entities/gtav_blazer.lua
  lua/entities/gtav_gauntlet_classic.lua
  lua/entities/gtav_insurgent.lua
  lua/entities/gtav_sanchez.lua
  lua/entities/gtav_speedo.lua
  lua/entities/gtav_strikeforce.lua
  lua/entities/gtav_wolfsbane.lua
  lua/glide/server/util.lua
Labels: enhancement

#5 Add resource.AddWorkshop call to autorun
  lua/autorun/sh_glide.lua
Labels: enhancement

#6 Increase FOV limit, default FOV to fov_desired
  lua/glide/client/config.lua
Labels: enhancement

#7 Add `glide_gib_lifetime` convar
  lua/autorun/sh_glide.lua
  lua/entities/glide_gib.lua
Labels: enhancement

#9 Draw quads slightly backward for zfighting
  lua/glide/client/skybox_detector.lua
Labels: enhancement

#8 Index optimization
  lua/entities/base_glide/init.lua
  lua/entities/base_glide/shared.lua
  lua/entities/base_glide_aircraft/init.lua
  lua/entities/base_glide_car/init.lua
  lua/entities/base_glide_heli/init.lua
  lua/entities/base_glide_plane/init.lua
  lua/entities/base_glide_tank/init.lua
  lua/entities/glide_wheel/cl_init.lua
  lua/entities/glide_wheel/init.lua
  lua/glide/server/input.lua
  lua/glide/server/weaponry.lua
  lua/glide/sh_anims.lua
  lua/glide/sh_player.lua
Labels: enhancement

#11 Add driver/seat-related wire outputs
  lua/entities/base_glide/init.lua
  lua/entities/base_glide/shared.lua
Labels: enhancement

#13 Added Turkish L10n
  resource/localization/tr/glide_vehicles.properties
Labels: enhancement

#14 Allow you to redefine vehicle spawn colors, again
  lua/entities/base_glide/init.lua
Labels: enhancement

#20 Updated Turkish L10n
  resource/localization/tr/glide_vehicles.properties
Labels: enhancement

#21 Allow you to define thirdperson camera center offset
  lua/entities/base_glide/shared.lua
  lua/glide/client/camera.lua
Labels: enhancement

#22 Updated Russian localization
  resource/localization/ru/glide_vehicles.properties
Labels: enhancement

#19 Weapon support for sit sequences
  lua/glide/sh_anims.lua
Labels: enhancement

#23 Add rotorwash logic
  lua/entities/base_glide_heli/init.lua
  lua/entities/glide_rotor.lua
Labels: enhancement

#24 Rotorwash fix
  lua/entities/base_glide/init.lua
  lua/entities/base_glide_aircraft/init.lua
  lua/entities/base_glide_heli/init.lua
  lua/entities/glide_rotor.lua
Labels: enhancement, bugfix

#27 Do watersplash trace for Glide.FireBullet
  lua/glide/server/weaponry.lua
Labels: enhancement

#28 Prevent glide_missile damaging glide_missile
  lua/entities/glide_missile.lua
Labels: bugfix

#29 Allow overriding playertag name and color using hook
  lua/glide/client/target_info.lua
Labels: enhancement

#30 Add VJ Base NPC helper tags (Extra compatibility)
  lua/entities/base_glide/shared.lua
  lua/entities/base_glide_aircraft/shared.lua
  lua/entities/glide_missile.lua
  lua/entities/glide_projectile.lua
Labels: enhancement

#31 Delete projectiles/missiles on skybox hit
  lua/entities/glide_missile.lua
  lua/entities/glide_projectile.lua
Labels: enhancement

#32 Set glide icon for sweps
  lua/autorun/sh_glide.lua
Labels: enhancement

#35 Add cant fire state and reset lock on reload
  lua/weapons/glide_homing_launcher.lua
Labels: enhancement

#36 Do parent lookup for prop_vehicle_prisoner_pod, make logic cleaner
  lua/glide/server/weaponry.lua
Labels: enhancement

#37 Some improvements in Russian localization
  resource/localization/ru/glide_vehicles.properties
Labels: enhancement
